version: 2
dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Install dependencies
          command: apt-get update && apt-get install doxygen graphviz git -y
      - run:
          name: Run the script
          command: ls -lah && bash generateDocumentationAndDeployCircle.sh

